// Auto generated by godot-rust-tools at 2025-09-02T19:51:22

#[allow(unused)]
pub struct InputActions;

#[allow(unused)]
impl InputActions {
	pub const SOME_ACTION: &'static str = "some action"; 
} 

#[allow(unused)]
pub struct Groups;

#[allow(unused)]
impl Groups {
	pub const SOME_TEST_GROUP: &'static str = "some test group"; 
} 

#[allow(unused)]
pub struct Render2dLayers;

#[allow(unused)]
impl Render2dLayers {
	pub const REN_DER_ER: u32 = 1 << 0; 
} 

#[allow(unused)]
pub struct Render3dLayers;

#[allow(unused)]
impl Render3dLayers {
	pub const RENDER_3D: u32 = 1 << 0; 
} 

#[allow(unused)]
pub struct Physics2dLayers;

#[allow(unused)]
impl Physics2dLayers {
	pub const MY_COOL_LAYER_NAME_OR_SOMETHING: u32 = 1 << 0; 
} 

#[allow(unused)]
pub struct Physics3dLayers;

#[allow(unused)]
impl Physics3dLayers {
	pub const MY_COOL_PHYSICS_LAYER: u32 = 1 << 0; 
	pub const MY_OTHER_EQUALLY_COOL_PHYSICS_LAYER: u32 = 1 << 1; 
} 

#[allow(unused)]
pub struct Navigation3dLayers;

#[allow(unused)]
impl Navigation3dLayers {
	pub const NAVIGATION_LAYER_I_GUESS: u32 = 1 << 0; 
} 

#[allow(unused)]
pub struct AvoidanceLayers;

#[allow(unused)]
impl AvoidanceLayers {
	pub const AVOIDANCE_LAYER_A: u32 = 1 << 0; 
} 
