// Auto generated by godot-rust-tools at 2025-09-10T14:57:44
#![rustfmt::skip]
#![allow(unused)]

pub mod input_actions {
    pub const UI_ACCEPT: &'static str = "ui_accept";
    pub const UI_SELECT: &'static str = "ui_select";
    pub const UI_CANCEL: &'static str = "ui_cancel";
    pub const UI_FOCUS_NEXT: &'static str = "ui_focus_next";
    pub const UI_FOCUS_PREV: &'static str = "ui_focus_prev";
    pub const UI_LEFT: &'static str = "ui_left";
    pub const UI_RIGHT: &'static str = "ui_right";
    pub const UI_UP: &'static str = "ui_up";
    pub const UI_DOWN: &'static str = "ui_down";
    pub const UI_PAGE_UP: &'static str = "ui_page_up";
    pub const UI_PAGE_DOWN: &'static str = "ui_page_down";
    pub const UI_HOME: &'static str = "ui_home";
    pub const UI_END: &'static str = "ui_end";
    pub const UI_ACCESSIBILITY_DRAG_AND_DROP: &'static str = "ui_accessibility_drag_and_drop";
    pub const UI_CUT: &'static str = "ui_cut";
    pub const UI_COPY: &'static str = "ui_copy";
    pub const UI_FOCUS_MODE: &'static str = "ui_focus_mode";
    pub const UI_PASTE: &'static str = "ui_paste";
    pub const UI_UNDO: &'static str = "ui_undo";
    pub const UI_REDO: &'static str = "ui_redo";
    pub const UI_TEXT_COMPLETION_QUERY: &'static str = "ui_text_completion_query";
    pub const UI_TEXT_COMPLETION_ACCEPT: &'static str = "ui_text_completion_accept";
    pub const UI_TEXT_COMPLETION_REPLACE: &'static str = "ui_text_completion_replace";
    pub const UI_TEXT_NEWLINE: &'static str = "ui_text_newline";
    pub const UI_TEXT_NEWLINE_BLANK: &'static str = "ui_text_newline_blank";
    pub const UI_TEXT_NEWLINE_ABOVE: &'static str = "ui_text_newline_above";
    pub const UI_TEXT_INDENT: &'static str = "ui_text_indent";
    pub const UI_TEXT_DEDENT: &'static str = "ui_text_dedent";
    pub const UI_TEXT_BACKSPACE: &'static str = "ui_text_backspace";
    pub const UI_TEXT_BACKSPACE_WORD: &'static str = "ui_text_backspace_word";
    pub const UI_TEXT_BACKSPACE_WORD_MACOS: &'static str = "ui_text_backspace_word.macos";
    pub const UI_TEXT_BACKSPACE_ALL_TO_LEFT: &'static str = "ui_text_backspace_all_to_left";
    pub const UI_TEXT_BACKSPACE_ALL_TO_LEFT_MACOS: &'static str = "ui_text_backspace_all_to_left.macos";
    pub const UI_TEXT_DELETE: &'static str = "ui_text_delete";
    pub const UI_TEXT_DELETE_WORD: &'static str = "ui_text_delete_word";
    pub const UI_TEXT_DELETE_WORD_MACOS: &'static str = "ui_text_delete_word.macos";
    pub const UI_TEXT_DELETE_ALL_TO_RIGHT: &'static str = "ui_text_delete_all_to_right";
    pub const UI_TEXT_DELETE_ALL_TO_RIGHT_MACOS: &'static str = "ui_text_delete_all_to_right.macos";
    pub const UI_TEXT_CARET_LEFT: &'static str = "ui_text_caret_left";
    pub const UI_TEXT_CARET_WORD_LEFT: &'static str = "ui_text_caret_word_left";
    pub const UI_TEXT_CARET_WORD_LEFT_MACOS: &'static str = "ui_text_caret_word_left.macos";
    pub const UI_TEXT_CARET_RIGHT: &'static str = "ui_text_caret_right";
    pub const UI_TEXT_CARET_WORD_RIGHT: &'static str = "ui_text_caret_word_right";
    pub const UI_TEXT_CARET_WORD_RIGHT_MACOS: &'static str = "ui_text_caret_word_right.macos";
    pub const UI_TEXT_CARET_UP: &'static str = "ui_text_caret_up";
    pub const UI_TEXT_CARET_DOWN: &'static str = "ui_text_caret_down";
    pub const UI_TEXT_CARET_LINE_START: &'static str = "ui_text_caret_line_start";
    pub const UI_TEXT_CARET_LINE_START_MACOS: &'static str = "ui_text_caret_line_start.macos";
    pub const UI_TEXT_CARET_LINE_END: &'static str = "ui_text_caret_line_end";
    pub const UI_TEXT_CARET_LINE_END_MACOS: &'static str = "ui_text_caret_line_end.macos";
    pub const UI_TEXT_CARET_PAGE_UP: &'static str = "ui_text_caret_page_up";
    pub const UI_TEXT_CARET_PAGE_DOWN: &'static str = "ui_text_caret_page_down";
    pub const UI_TEXT_CARET_DOCUMENT_START: &'static str = "ui_text_caret_document_start";
    pub const UI_TEXT_CARET_DOCUMENT_START_MACOS: &'static str = "ui_text_caret_document_start.macos";
    pub const UI_TEXT_CARET_DOCUMENT_END: &'static str = "ui_text_caret_document_end";
    pub const UI_TEXT_CARET_DOCUMENT_END_MACOS: &'static str = "ui_text_caret_document_end.macos";
    pub const UI_TEXT_CARET_ADD_BELOW: &'static str = "ui_text_caret_add_below";
    pub const UI_TEXT_CARET_ADD_BELOW_MACOS: &'static str = "ui_text_caret_add_below.macos";
    pub const UI_TEXT_CARET_ADD_ABOVE: &'static str = "ui_text_caret_add_above";
    pub const UI_TEXT_CARET_ADD_ABOVE_MACOS: &'static str = "ui_text_caret_add_above.macos";
    pub const UI_TEXT_SCROLL_UP: &'static str = "ui_text_scroll_up";
    pub const UI_TEXT_SCROLL_UP_MACOS: &'static str = "ui_text_scroll_up.macos";
    pub const UI_TEXT_SCROLL_DOWN: &'static str = "ui_text_scroll_down";
    pub const UI_TEXT_SCROLL_DOWN_MACOS: &'static str = "ui_text_scroll_down.macos";
    pub const UI_TEXT_SELECT_ALL: &'static str = "ui_text_select_all";
    pub const UI_TEXT_SELECT_WORD_UNDER_CARET: &'static str = "ui_text_select_word_under_caret";
    pub const UI_TEXT_SELECT_WORD_UNDER_CARET_MACOS: &'static str = "ui_text_select_word_under_caret.macos";
    pub const UI_TEXT_ADD_SELECTION_FOR_NEXT_OCCURRENCE: &'static str = "ui_text_add_selection_for_next_occurrence";
    pub const UI_TEXT_SKIP_SELECTION_FOR_NEXT_OCCURRENCE: &'static str = "ui_text_skip_selection_for_next_occurrence";
    pub const UI_TEXT_CLEAR_CARETS_AND_SELECTION: &'static str = "ui_text_clear_carets_and_selection";
    pub const UI_TEXT_TOGGLE_INSERT_MODE: &'static str = "ui_text_toggle_insert_mode";
    pub const UI_MENU: &'static str = "ui_menu";
    pub const UI_TEXT_SUBMIT: &'static str = "ui_text_submit";
    pub const UI_UNICODE_START: &'static str = "ui_unicode_start";
    pub const UI_GRAPH_DUPLICATE: &'static str = "ui_graph_duplicate";
    pub const UI_GRAPH_DELETE: &'static str = "ui_graph_delete";
    pub const UI_GRAPH_FOLLOW_LEFT: &'static str = "ui_graph_follow_left";
    pub const UI_GRAPH_FOLLOW_LEFT_MACOS: &'static str = "ui_graph_follow_left.macos";
    pub const UI_GRAPH_FOLLOW_RIGHT: &'static str = "ui_graph_follow_right";
    pub const UI_GRAPH_FOLLOW_RIGHT_MACOS: &'static str = "ui_graph_follow_right.macos";
    pub const UI_FILEDIALOG_UP_ONE_LEVEL: &'static str = "ui_filedialog_up_one_level";
    pub const UI_FILEDIALOG_REFRESH: &'static str = "ui_filedialog_refresh";
    pub const UI_FILEDIALOG_SHOW_HIDDEN: &'static str = "ui_filedialog_show_hidden";
    pub const UI_SWAP_INPUT_DIRECTION: &'static str = "ui_swap_input_direction";
    pub const UI_COLORPICKER_DELETE_PRESET: &'static str = "ui_colorpicker_delete_preset";
    pub const SOME_ACTION: &'static str = "some action";
    pub const ADF: &'static str = "adf";
}

pub mod groups {
    pub const SOME_TEST_GROUP: &'static str = "some test group";
}

pub mod render_2d_layers {
    pub const REN_DER_ER: u32 = 0;
}

pub mod render_3d_layers {
    pub const RENDER_3D: u32 = 0;
}

pub mod physics_2d_layers {
    pub const MY_COOL_LAYER_NAME_OR_SOMETHING: u32 = 0;
}

pub mod physics_3d_layers {
    pub const MY_COOL_PHYSICS_LAYER: u32 = 0;
    pub const MY_OTHER_EQUALLY_COOL_PHYSICS_LAYER: u32 = 1;
}

pub mod navigation_3d_layers {
    pub const NAVIGATION_LAYER_I_GUESS: u32 = 0;
}

pub mod avoidance_layers {
    pub const AVOIDANCE_LAYER_A: u32 = 0;
}
